### ISSUE TITLE
Search queries are not returning results from Cognitive Search Service Indexer and Index

### ISSUE THREAD

**Issue by heartleaf** [Azure-Samples/azure-search-knowledge-mining#98]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Followed the Azure search knowledge mining steps, ran into issues in Cognitive UI wherein results are not displayed in UI of scanned documents or search query is not functioning as expected.

### Any log messages given by the failure
>DataPlaneApiArgumentException : Unknown field '<IPICpYR4fYAB>' in facet specification.
Parameter name: facet.
Stack:
at Microsoft.WindowsAzure.Search.Core.Services.FacetParser.ParseFacet(CustomerData facetSpecification) in d:\dbs\el\mbas\Source\Search\Product\SearchCore\Services\FacetParser.cs:line 85
at Microsoft.WindowsAzure.Search.Core.Services.FacetParser.ParseFacets(CustomerData[] facetSpecifications) in d:\dbs\el\mbas\Source\Search\Product\SearchCore\Services\FacetParser.cs:line 45
at Microsoft.WindowsAzure.Search.Core.Services.QueryBuilder.BuildSearchQuery(ApiSearchQuery apiSearchQuery) in d:\dbs\el\mbas\Source\Search\Product\SearchCore.WebApi.Windows\Services\QueryBuilder.cs:line 172
at Microsoft.WindowsAzure.Search.Core.Controllers.QueryControllerImpl.<>c__DisplayClass16_0.<SearchAsync>b__0(Index index) in d:\dbs\el\mbas\Source\Search\Product\SearchCore.WebApi.Windows\Controllers\QueryControllerImpl.cs:line 90
at Microsoft.WindowsAzure.Search.Core.Controllers.QueryControllerImpl.<ExecuteSearchAsync>d__24`1.MoveNext() in d:\dbs\el\mbas\Source\Search\Product\SearchCore.WebApi.Windows\Controllers\QueryControllerImpl.cs:line 233
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.WindowsAzure.Search.Core.Controllers.QueryControllerImpl.<SearchAsync>d__16.MoveNext() in d:\dbs\el\mbas\Source\Search\Product\SearchCore.WebApi.Windows\Controllers\QueryControllerImpl.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.WindowsAzure.Search.Core.Controllers.Docs20200630Controller.<Get>d__10.MoveNext() in d:\dbs\el\mbas\Source\Search\Product\SearchCore.WebApi.Windows\Controllers\2020-06-30\Docs20200630Controller.cs:line 100
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.WindowsAzure.Search.Core.Controllers.Docs20200630Controller.<Search>d__9.MoveNext() in d:\dbs\el\mbas\Source\Search\Product\SearchCore.WebApi.Windows\Controllers\2020-06-30\Docs20200630Controller.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.Http.ExceptionHandlingActionInvoker.<InvokeActionAsync>d__0.MoveNext() in d:\dbs\el\mbas\Source\Hosting\Product\AzureSearch.Hosting.AspNet.Windows\Http\ExceptionHandlingActionInvoker.cs:line 22

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?) 
Azure Apps Service Windows

### Versions
> Win

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment]
I'm not able to reproduce this on my end. It looks like the query is trying to append on a facet with no name to the query.

Did you make any changes to **SearchModel.cs**? The facets array in that file determines which fields are added to the query. If you leave the array empty, all facetable fields will be used in the query. If you list fields in that array, then those fields will be used at query time. You could try setting this to a single facetable field too to see if that helps (make sure to check your index definition in the portal to ensure the field is actually facetable.

```C#
        private string[] facets = new string[]
        {
            // Add UI facets here in order
            //"people", 
            //"locations",
            //"organizations",
            //"keyphrases"
        };
```

**Comment by heartleaf** [comment]
Hi Derek, Troubleshooting tip you offered to add break point at Line 103 in the documentSearch.cs helped identify the root cause, as I was stepping through the code noticed an error on missing metadata_title, so I went back and checked the field that helped resolve the web UI display problem. Thanks a bunch.

**Comment by dereklegenzoff** [comment]
Glad you were able to get it figured out! I appreciate you letting me know that that fixed it for you. I'll make a note to add a troubleshooting.md file or something similar to this repo with common things to check when issues arise; i think that could make it easier to debug when things aren't working as expected.
